name: Check / auto apply Black
on:
  push:
    branches:
    - main

jobs:
  black:
    name: Check / auto apply black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: psf/black@stable
        id: black
        with:
          options: "."
        continue-on-error: true
      - shell: pwsh
        id: check_files_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff
          $HasDiff = $diff.Length -gt 0
          Write-Host "::set-output name=files_changed::$HasDiff"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":art: Format Python code with Black"
          commit_user_name: yunohost-bot
          commit_user_email: yunohost-bot@users.noreply.github.com
          commit_author: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
